### PR TITLE
Added Docker Step Through to the readme file

### PR DESCRIPTION
**Pull request by JQH84**
This PR consists of the following changes :
1. Modified the YML file to reflect the correct ports for my system for Postgres
2. Added a quick step through on how to setup Docker and test the containers

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @JQH84, I'll review the changes right away.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update "docker-compose.yml". Please make sure to revert your changes before merging your PR.

**Comment by JQH84** [comment]
i need to have that yml file changed as I only changed the postgres port

**Review by vanessa-cooper — APPROVED** [review]
Awesome! Thanks so much for taking the time to make the setup experience a little smoother. Hopefully, new engineers will now have a much easier time🌟.
Now, all that’s left is to merge this PR and the next item will be ready for you in Snack.

**Pull request merged**
